# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['src/meikipop/main.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('src/meikipop/ocr/providers/glensv2/provider.py', 'meikipop/ocr/providers/glensv2'),
        ('src/meikipop/ocr/providers/glensv2/lens_betterproto.py', 'meikipop/ocr/providers/glensv2'),
        ('src/meikipop/ocr/providers/glensv2/__init__.py', 'meikipop/ocr/providers/glensv2'),
        ('src/meikipop/ocr/providers/owocr/provider.py', 'meikipop/ocr/providers/owocr'),
        ('src/meikipop/ocr/providers/owocr/__init__.py', 'meikipop/ocr/providers/owocr'),
        ('src/meikipop/ocr/providers/meikiocr/provider.py', 'meikipop/ocr/providers/meikiocr'),
        ('src/meikipop/ocr/providers/meikiocr/__init__.py', 'meikipop/ocr/providers/meikiocr'),
        ('src/meikipop/ocr/providers/meikiocr/vertical.py', 'meikipop/ocr/providers/meikiocr'),
        ('src/meikipop/ocr/providers/screenai/provider.py', 'meikipop/ocr/providers/screenai'),
        ('src/meikipop/ocr/providers/screenai/chrome_screen_ai_pb2.py', 'meikipop/ocr/providers/screenai'),
        ('src/meikipop/ocr/providers/screenai/view_hierarchy_pb2.py', 'meikipop/ocr/providers/screenai'),
        ('src/meikipop/ocr/providers/screenai/__init__.py', 'meikipop/ocr/providers/screenai'),
        ('src/meikipop/ocr/providers/__init__.py', 'meikipop/ocr/providers'),
        ('src/meikipop/resources/icon.ico', 'meikipop/resources'),
        ('src/meikipop/resources/icon.inactive.ico', 'meikipop/resources'),
        ('src/meikipop/scripts/deconjugator.json', 'meikipop/scripts'),
    ],
    hiddenimports=['meikipop.ocr.providers.glensv2', 'meikipop.ocr.providers.owocr', 'meikipop.ocr.providers.meikiocr', 'meikipop.ocr.providers.meikiocr.vertical', 'meikipop.ocr.providers.screenai'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='meikipop',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)